// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

const (
	NotificationTypeSuccess = iota
	NotificationTypeError
)

type NotificationProps struct {
	TypeMsg int
	Message string
}

func NotificationStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n    .error-box {\n        background-color: #fee2e2;\n        border: 1px solid #f87171;\n        color: #b91c1c;\n        padding: 0.75rem 1rem;\n        border-radius: 0.25rem;\n        position: relative;\n    }\n\n    .error-box .error-title {\n        font-weight: 700;\n    }\n\n    .error-box .error-message {\n        display: block;\n    }\n\n    @media (min-width: 640px) {\n        .error-box .error-message {\n            display: inline;\n        }\n    }\n\n    .error-box .close-btn {\n        position: absolute;\n        top: 0;\n        bottom: 0;\n        right: 0;\n        padding: 0.75rem 1rem;\n    }\n\n    .error-box .close-btn svg {\n        fill: currentColor;\n        height: 1.5rem;\n        width: 1.5rem;\n        color: #ef4444;\n    }\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
